apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: sujithes/platformservice:latest
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
  - name:  platformservice
    port:  80
    protocol: TCP
    targetPort: 80
  - name: platformgrpc
    port:  666
    protocol: TCP
    targetPort: 666
